[build]
  publish = "dist"
  functions = "netlify/functions"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "20"
  SUPABASE_URL = "${SUPABASE_URL}"
  SUPABASE_SERVICE_ROLE_KEY = "${SUPABASE_SERVICE_ROLE_KEY}"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[functions]
  directory = "api"
  node_bundler = "esbuild"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Force redeploy for API functions - 2025-06-26

