[build]
  command = "npm install --no-frozen-lockfile && npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-frozen-lockfile"
  NETLIFY_BUILD_DEBUG = "true"

[functions]
  directory = "netlify/functions"
  external_node_modules = ["@upstash/redis", "xrpl", "ioredis", "redis", "@supabase/supabase-js", "bcryptjs", "jsonwebtoken", "crypto-js", "axios"]
  included_files = ["netlify/functions/**/*"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

